collections:
  - name: community.general
  - name: community.windows
  - name: ansible.posix
  - name: community.vmware

roles:
  - src: git+https://github.com/bertvv/ansible-role-dhcp.git
    name: bertvv.dhcp
  - src: git+https://github.com/bertvv/ansible-role-radvd.git
    name: bertvv.radvd