collections:
  - name: community.general
  - name: community.windows
  - name: ansible.posix
  - name: community.vmware

# Roles comentados - no son necesarios, usamos roles propios
# roles:
#   - name: bertvv.dhcp
#   - name: debops.radvd
#   - name: bertvv.radvd