---
# Playbook para configurar solo el firewall
# Ejecutar: ansible-playbook firewall.yml --connection=local --become --ask-become-pass

- name: Configurar Firewall (UFW + fail2ban)
  hosts: localhost
  connection: local
  become: true
  
  roles:
    - role: firewall
      tags: firewall
