- name: Validar variables críticas
  hosts: all
  gather_facts: false
  tasks:
    - name: Verificar que vault_win_admin_password esté definida
      ansible.builtin.assert:
        that:
          - vault_win_admin_password is defined
          - vault_win_admin_password | length > 0
        fail_msg: "vault_win_admin_password no está definida en el vault"
        success_msg: "Credenciales del vault verificadas"
      when: "'windows_vms' in group_names or 'vmware_host' in group_names"

- name: Configurar red IPv6 en servidor Ubuntu
  hosts: ubuntu_server
  become: true
  vars:
    network_ipv6_interface: "ens33"
    network_ipv6_address: "2001:db8:1::10"
    network_ipv6_netmask: "64"
    network_ipv6_gateway: "2001:db8:1::1"
    network_ipv6_dns_servers:
      - "2001:4860:4860::8888"
      - "2001:4860:4860::8844"
    network_ipv6_domain: "localdomain"
  roles:
    - role: network_ipv6

- name: Configurar ajustes comunes y DHCP en servidor Ubuntu
  hosts: ubuntu_server
  become: true
  roles:
    - role: common
    - role: dhcpv6
    - role: procesos
    - role: storage
    - role: firewall

- name: Crear VM Ubuntu en VMware vSphere
  hosts: vmware_host
  connection: local
  gather_facts: false
  roles:
    - role: vmware
