---
# Playbook principal para configurar servicios IPv6
# Red: 2025:db8:10::/64
# nota importante - 2025:db8:10::2 

- name: Mostrar información de la configuración
  hosts: all
  gather_facts: false
  tasks:
    - name: Información de red IPv6
      debug:
        msg: |
           Configuración de red:
          - Red: {{ network_config.ipv6_network }}
          - Gateway: {{ network_config.ipv6_gateway }}
          - DHCP desde: {{ network_config.dhcp_range_start }}
          - Dominio: {{ network_config.domain_name }}

- name: Configurar servicios completos en servidor Ubuntu
  hosts: servidores_ubuntu
  become: true
  roles:
    - role: common
    - role: dns_bind
    - role: dhcpv6
    - role: firewall
    - role: procesos
    - role: storage

- name: Crear VM Ubuntu en VMware ESXi
  hosts: vmware_servers
  connection: local
  gather_facts: false
  vars_files:
    - group_vars/ubpc.yml
  roles:
    - role: vmware
  tags: create_vm

- name: Configurar servicios en nueva VM UBPC (después de instalación manual)
  hosts: nueva_vm_ubpc
  become: true
  roles:
    - role: common
    - role: dns_bind
    - role: dhcpv6
    - role: firewall
    - role: procesos
    - role: storage
  tags: configure_vm
