---
# Playbook interactivo para configurar servicios IPv6 en el servidor local
# Red: 2025:db8:10::/64

- name: Configurar servidor Ubuntu con servicios de red (Modo Interactivo)
  hosts: localhost
  connection: local
  become: true
  
  vars:
    interactive_mode: true
  
  tasks:
    - name: "๐ฏ Bienvenida"
      debug:
        msg:
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - "โ        ๐ฎ GameCenter - Configuraciรณn del Servidor           โ"
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - ""
          - "Este playbook configurarรก:"
          - "  1. Paquetes comunes del sistema"
          - "  2. Red IPv6 en ens34"
          - "  3. Servidor DNS (BIND9)"
          - "  4. Servidor DHCP IPv6"
          - "  5. Firewall (UFW + fail2ban)"
          - "  6. Almacenamiento NFS"
          - ""
          - "Configuraciรณn:"
          - "  Red IPv6: {{ network_config.ipv6_network }}"
          - "  Gateway: {{ network_config.ipv6_gateway }}"
          - "  DHCP desde: {{ network_config.dhcp_range_start }}"
          - "  Dominio: {{ network_config.domain_name }}"
          - ""
    
    - name: "โธ๏ธ  Pausa antes de comenzar"
      pause:
        prompt: "Presiona ENTER para comenzar la configuraciรณn..."
      when: interactive_mode | default(false)
    
    # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
    # ROL 1: COMMON
    # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
    
    - name: "๐ฆ Paso 1/6: Instalando paquetes comunes"
      debug:
        msg:
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - "โ  ๐ฆ Paso 1: Paquetes Comunes del Sistema                    โ"
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - ""
          - "Instalarรก:"
          - "  โข vim, git, curl, wget"
          - "  โข net-tools, dnsutils"
          - "  โข python3-pip"
          - "  โข Actualizarรก el sistema"
    
    - name: "โธ๏ธ  Continuar con instalaciรณn de paquetes?"
      pause:
        prompt: "Presiona ENTER para instalar paquetes comunes..."
      when: interactive_mode | default(false)
    
    - name: "Ejecutar rol: common"
      include_role:
        name: common
    
    - name: "โ Paquetes comunes instalados"
      debug:
        msg:
          - "โ Paquetes comunes instalados correctamente"
          - ""
    
    # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
    # ROL 2: NETWORK
    # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
    
    - name: "๐ Paso 2/6: Configurando red IPv6"
      debug:
        msg:
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - "โ  ๐ Paso 2: Configuraciรณn de Red IPv6                       โ"
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - ""
          - "Configurarรก:"
          - "  โข Interfaz WAN (ens33): IPv4 DHCP (internet)"
          - "  โข Interfaz LAN (ens34): IPv6 {{ network_config.ipv6_network }}"
          - "  โข IP del servidor: 2025:db8:10::2/64"
          - "  โข IP forwarding habilitado"
          - "  โข NAT66 para que las VMs salgan a internet"
          - ""
          - "โ๏ธ  IMPORTANTE: Esto aplicarรก cambios de red con netplan"
    
    - name: "โธ๏ธ  Continuar con configuraciรณn de red?"
      pause:
        prompt: "Presiona ENTER para configurar la red..."
      when: interactive_mode | default(false)
    
    - name: "Ejecutar rol: network"
      include_role:
        name: network
    
    - name: "โ Red configurada"
      debug:
        msg:
          - "โ Red IPv6 configurada correctamente"
          - ""
          - "Verifica con: ip -6 addr show ens34"
          - ""
    
    # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
    # ROL 3: DNS
    # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
    
    - name: "๐ Paso 3/6: Configurando DNS"
      debug:
        msg:
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - "โ  ๐ Paso 3: Servidor DNS (BIND9)                            โ"
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - ""
          - "Configurarรก:"
          - "  โข BIND9 como servidor DNS"
          - "  โข Zona: {{ network_config.domain_name }}"
          - "  โข Resoluciรณn de nombres para VMs"
          - "  โข Forwarders a DNS pรบblicos"
          - ""
    
    - name: "โธ๏ธ  Continuar con DNS?"
      pause:
        prompt: "Presiona ENTER para configurar DNS..."
      when: interactive_mode | default(false)
    
    - name: "Ejecutar rol: dns_bind"
      include_role:
        name: dns_bind
    
    - name: "โ DNS configurado"
      debug:
        msg:
          - "โ Servidor DNS configurado correctamente"
          - ""
          - "Verifica con: sudo systemctl status named"
          - ""
    
    # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
    # ROL 4: DHCP
    # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
    
    - name: "๐ก Paso 4/6: Configurando DHCP IPv6"
      debug:
        msg:
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - "โ  ๐ก Paso 4: Servidor DHCP IPv6                              โ"
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - ""
          - "Configurarรก:"
          - "  โข ISC DHCP Server para IPv6"
          - "  โข Rango: {{ network_config.dhcp_range_start }} - {{ network_config.dhcp_range_end }}"
          - "  โข Asignaciรณn automรกtica de IPs a VMs"
          - "  โข DNS automรกtico"
          - ""
    
    - name: "โธ๏ธ  Continuar con DHCP?"
      pause:
        prompt: "Presiona ENTER para configurar DHCP..."
      when: interactive_mode | default(false)
    
    - name: "Ejecutar rol: dhcpv6"
      include_role:
        name: dhcpv6
    
    - name: "โ DHCP configurado"
      debug:
        msg:
          - "โ Servidor DHCP IPv6 configurado correctamente"
          - ""
          - "Verifica con: sudo systemctl status isc-dhcp-server6"
          - ""
    
    # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
    # ROL 5: FIREWALL
    # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
    
    - name: "๐ฅ Paso 5/6: Configurando Firewall"
      debug:
        msg:
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - "โ  ๐ฅ Paso 5: Firewall (UFW + fail2ban)                       โ"
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - ""
          - "Configurarรก:"
          - "  โข UFW (Uncomplicated Firewall)"
          - "  โข Reglas para SSH, DNS, DHCP"
          - "  โข fail2ban para protecciรณn contra ataques"
          - "  โข Rate limiting en SSH"
          - ""
          - "โ๏ธ  IMPORTANTE: Asegรบrate de tener acceso SSH antes de continuar"
    
    - name: "โธ๏ธ  Continuar con Firewall?"
      pause:
        prompt: "Presiona ENTER para configurar el firewall..."
      when: interactive_mode | default(false)
    
    - name: "Ejecutar rol: firewall"
      include_role:
        name: firewall
    
    - name: "โ Firewall configurado"
      debug:
        msg:
          - "โ Firewall configurado correctamente"
          - ""
          - "Verifica con: sudo ufw status verbose"
          - ""
    
    # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
    # ROL 6: STORAGE
    # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
    
    - name: "๐พ Paso 6/6: Configurando almacenamiento"
      debug:
        msg:
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - "โ  ๐พ Paso 6: Almacenamiento NFS                              โ"
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - ""
          - "Configurarรก:"
          - "  โข Servidor NFS"
          - "  โข Compartir directorios para VMs"
          - "  โข Permisos adecuados"
          - ""
    
    - name: "โธ๏ธ  Continuar con Storage?"
      pause:
        prompt: "Presiona ENTER para configurar almacenamiento..."
      when: interactive_mode | default(false)
    
    - name: "Ejecutar rol: storage"
      include_role:
        name: storage
    
    - name: "โ Storage configurado"
      debug:
        msg:
          - "โ Almacenamiento NFS configurado correctamente"
          - ""
    
    # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
    # RESUMEN FINAL
    # โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
    
    - name: "๐ Configuraciรณn completada"
      debug:
        msg:
          - ""
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - "โ              โ CONFIGURACIรN COMPLETADA                     โ"
          - "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          - ""
          - "Servicios configurados:"
          - "  โ Paquetes comunes instalados"
          - "  โ Red IPv6 en ens34 (2025:db8:10::2/64)"
          - "  โ DNS (BIND9) funcionando"
          - "  โ DHCP IPv6 asignando IPs"
          - "  โ Firewall activo y configurado"
          - "  โ Almacenamiento NFS disponible"
          - ""
          - "Comandos รบtiles:"
          - "  โข Ver IPv6: ip -6 addr show ens34"
          - "  โข Ver firewall: sudo ufw status verbose"
          - "  โข Ver DNS: sudo systemctl status named"
          - "  โข Ver DHCP: sudo systemctl status isc-dhcp-server6"
          - "  โข Ver NAT: sudo ip6tables -t nat -L -v"
          - ""
          - "El servidor estรก listo para crear VMs! ๐"
          - ""
