- name: Validar variables críticas
  hosts: all
  gather_facts: false
  tasks:
    - name: Verificar que vault_win_admin_password esté definida
      ansible.builtin.assert:
        that:
          - vault_win_admin_password is defined
          - vault_win_admin_password | length > 0
        fail_msg: "vault_win_admin_password no está definida en el vault"
        success_msg: "Credenciales del vault verificadas"
      when: "'windows_vms' in group_names or 'vbox_host' in group_names"

- name: Configurar ajustes comunes y DHCP en servidor Ubuntu
  hosts: ubuntu_server
  become: true
  roles:
    - role: common
    - role: dhcp
    - role: radvd
    - role: procesos
    - role: storage

- name: Crear VM de Windows 11 en host VirtualBox
  hosts: vbox_host
  gather_facts: false
  roles:
    - role: virtualbox

- name: Post-configuración de VMs Windows
  hosts: windows_vms
  gather_facts: false
  vars:
    ansible_user: "{{ win_admin_user }}"
    ansible_password: "{{ win_admin_password }}"
  roles:
    - role: windows
