---
# Playbook principal para configurar servicios IPv6 en el servidor local
# Red: 2025:db8:10::/64
# IMPORTANTE: Ejecutar DENTRO del servidor Ubuntu (no desde PC remoto)
# Comando: ansible-playbook site.yml --connection=local --become --ask-become-pass

- name: Configurar servidor Ubuntu con servicios de red
  hosts: localhost
  connection: local
  become: true
  
  tasks:
    - name: Mostrar información de la configuración
      debug:
        msg:
          - "════════════════════════════════════════"
          - "Configurando servidor GameCenter"
          - "════════════════════════════════════════"
          - "Red IPv6: {{ network_config.ipv6_network }}"
          - "Gateway: {{ network_config.ipv6_gateway }}"
          - "DHCP desde: {{ network_config.dhcp_range_start }}"
          - "Dominio: {{ network_config.domain_name }}"
          - "════════════════════════════════════════"
  
  roles:
    - role: common
    - role: network
    - role: dns_bind
    - role: dhcpv6
    - role: firewall
    - role: storage
