- name: Provisionar VM Windows en host VirtualBox y post-configurar Windows
  hosts: vbox_host
  gather_facts: false
  roles:
    - role: virtualbox

- name: Post-configuración de Windows en la VM
  hosts: windows_vms
  gather_facts: false
  vars:
    ansible_user: "{{ win_admin_user }}"
    ansible_password: "{{ win_admin_password }}"
  roles:
    - role: windows
