- name: Install DHCP server
  ansible.builtin.apt:
    name: isc-dhcp-server
    state: present
    update_cache: yes

- name: Configure ISC DHCP server defaults
  ansible.builtin.template:
    src: isc-dhcp-server.default.j2
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: "0644"
  notify: Restart isc-dhcp-server

- name: Render dhcpd.conf
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart isc-dhcp-server
  when: dhcp is defined and dhcp.subnets is defined and (dhcp.subnets | length) > 0

- name: Render dhcpd6.conf (IPv6) when dhcp_v6 is defined
  ansible.builtin.template:
    src: dhcpd6.conf.j2
    dest: /etc/dhcp/dhcpd6.conf
    owner: root
    group: root
    mode: "0644"
  when: dhcp_v6 is defined and dhcp_v6.subnets is defined
  notify: Restart isc-dhcp-server6

- name: Enable and start DHCP service
  ansible.builtin.service:
    name: isc-dhcp-server
    state: started
    enabled: yes
  when: dhcp is defined and dhcp.subnets is defined and (dhcp.subnets | length) > 0

- name: Enable and start DHCPv6 service when dhcp_v6 is defined
  ansible.builtin.service:
    name: isc-dhcp-server6
    state: started
    enabled: yes
  when: dhcp_v6 is defined and dhcp_v6.subnets is defined
