- name: Install radvd
  ansible.builtin.apt:
    name: radvd
    state: present
    update_cache: yes

- name: Render radvd.conf
  ansible.builtin.template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart radvd

- name: Enable and start radvd
  ansible.builtin.service:
    name: radvd
    state: started
    enabled: yes
