- name: Ensure Windows admin user exists
  ansible.windows.win_user:
    name: "{{ win_admin_user }}"
    password: "{{ win_admin_password }}"
    state: present
    groups:
      - Administrators
    password_never_expires: true
    update_password: always

- name: Ensure WinRM service is running
  ansible.windows.win_service:
    name: WinRM
    state: started
    start_mode: auto

- name: Set timezone to SA Pacific Standard Time
  ansible.windows.win_timezone:
    timezone: SA Pacific Standard Time

- name: Ensure pcgamer user exists and is local admin
  ansible.windows.win_user:
    name: pcgamer
    password: "{{ win_admin_password }}"
    state: present
    groups:
      - Administrators
      - Remote Desktop Users
    password_never_expires: true
    update_password: on_create

- name: Enable Remote Desktop (allow RDP connections)
  ansible.windows.win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Terminal Server
    name: fDenyTSConnections
    data: 0
    type: dword

- name: Enable Windows Firewall rules for Remote Desktop group
  ansible.windows.win_shell: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
  args:
    executable: powershell.exe

- name: Install Windows Security and Critical updates
  ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
    state: installed
  register: winupd

- name: Reboot if required by updates
  ansible.windows.win_reboot:
  when: winupd.reboot_required | default(false)
